### ISSUE TITLE
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'android.util.Pair com.adtapsy.b.t.a(com.adtapsy.a.a.y, com.adtapsy.sdk.AdTapsyRewardedDelegate)' on a null object reference

### ISSUE THREAD

**Issue by ominfowave** [AdTapsy/AdTapsy-Android-SDK#2]
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'android.util.Pair com.adtapsy.b.t.a(com.adtapsy.a.a.y, com.adtapsy.sdk.AdTapsyRewardedDelegate)' on a null object reference
com.adtapsy.b.a.a (a.java)
<OR>.a (a.java)
<OR>.a (a.java)
<OR>.a (a.java)
<OR>.a (a.java)
<OR>.a (a.java)
<OR>.a (a.java)
<OR>.a (a.java)
<OR>.a (a.java)
<OR>.a (a.java)
<OR>.a (a.java)
<OR>.a (a.java)
com.adtapsy.b.m.a (m.java)
com.adtapsy.a.b.b.onPostExecute (b.java)
android.os.AsyncTask.finish (AsyncTask.java:651)
android.os.AsyncTask.access$500 (AsyncTask.java:180)
android.os.AsyncTask$InternalHandler.handleMessage (AsyncTask.java:668)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:7406)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)

**Comment by bgizdov** [comment]
I am closing this issue because it should be already fixed in the latest released versions.
